SELECT
    b.TITLE AS POST_TITLE,
    b.BOARD_ID AS POST_ID,
    r.REPLY_ID,
    r.WRITER_ID AS REPLY_WRITER_ID,
    r.CONTENTS AS REPLY_CONTENTS,
    DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS REPLY_CREATED_DATE
FROM
    USED_GOODS_BOARD b
JOIN
    USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
WHERE
    b.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY
    r.CREATED_DATE ASC,
    b.TITLE ASC;